### ISSUE TITLE
存储模板时NPE

### ISSUE THREAD

**Issue by code4craft** [gsh199449/spider#15]
在编辑模板页面编辑好后，点保存总是会出现/panel/commons/editSpiderInfo，每次都必现。
![image](https://cloud.githubusercontent.com/assets/1351884/21951805/296a785c-da48-11e6-8406-f113923f261c.png)
![image](https://cloud.githubusercontent.com/assets/1351884/21951811/3c8e10e2-da48-11e6-9582-59c21dc23b72.png)

```
java.lang.NullPointerException
	at com.gs.spider.dao.SpiderInfoDAO.getByDomain(SpiderInfoDAO.java:126)
	at com.gs.spider.dao.SpiderInfoDAO.index(SpiderInfoDAO.java:51)
	at com.gs.spider.service.commons.spiderinfo.SpiderInfoService.lambda$index$2(SpiderInfoService.java:58)
	at com.gs.spider.model.utils.ResultBundleBuilder.bundle(ResultBundleBuilder.java:25)
	at com.gs.spider.service.commons.spiderinfo.SpiderInfoService.index(SpiderInfoService.java:58)
	at com.gs.spider.controller.commons.spiderinfo.SpiderInfoController.save(SpiderInfoController.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

**Comment by code4craft** [comment]
似乎是我ES没配置好？难道不是用默认端口吗？

**Comment by gsh199449** [comment]
如果不配置es肯定是不能使用存储模板功能的。如果配置ES了还出空指针错误吗？

**Comment by gsh199449** [comment]
没有后续反馈，如果还有类似问题请再重新打开这个issue吧
