### ISSUE TITLE
运行项目报异常

### ISSUE THREAD

**Issue by EdronCai** [gsh199449/spider#3]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'commonSpider' defined in URL [file:/C:/Java/IdeaProjects/GatherPlatform/spider-master/target/spider/WEB-INF/classes/mvc-dispatcher-servlet.xml]: Cannot resolve reference to bean 'commonWebpageDAO' while setting bean property 'commonWebpageDAO'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'commonWebpageDAO' defined in file [C:\Java\IdeaProjects\GatherPlatform\spider-master\target\spider\WEB-INF\classes\com\gs\spider\dao\CommonWebpageDAO.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.gs.spider.dao.CommonWebpageDAO]: Constructor threw exception; nested exception is NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{y3YLXLvBRXGPiHARqVc2qQ}{127.0.0.1}{127.0.0.1:9300}]]

**Comment by gsh199449** [comment]
elasticsearch启动的时候报错了吗？

**Comment by EdronCai** [comment]
@gsh199449  启动的时候 也报错误了
正在初始化ElasticSearch客户端,localhost
 16:31:43[WARN org.springframework.web.context.support.XmlWebApplicationContext] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'commonSpider' defined in URL [file:/C:/Java/IdeaProjects/GatherPlatform/spider-master/target/spider/WEB-INF/classes/mvc-dispatcher-servlet.xml]: Cannot resolve reference to bean 'commonWebpageDAO' while setting bean property 'commonWebpageDAO'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'commonWebpageDAO' defined in file [C:\Java\IdeaProjects\GatherPlatform\spider-master\target\spider\WEB-INF\classes\com\gs\spider\dao\CommonWebpageDAO.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.gs.spider.dao.CommonWebpageDAO]: Constructor threw exception; nested exception is NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{Df0wvxy6SpW7auwH1zseug}{127.0.0.1}{127.0.0.1:9300}]]
 16:31:43[ERROR org.springframework.web.servlet.DispatcherServlet] Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'commonSpider' defined in URL [file:/C:/Java/IdeaProjects/GatherPlatform/spider-master/target/spider/WEB-INF/classes/mvc-dispatcher-servlet.xml]: Cannot resolve reference to bean 'commonWebpageDAO' while setting bean property 'commonWebpageDAO'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'commonWebpageDAO' defined in file [C:\Java\IdeaProjects\GatherPlatform\spider-master\target\spider\WEB-INF\classes\com\gs\spider\dao\CommonWebpageDAO.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.gs.spider.dao.CommonWebpageDAO]: Constructor threw exception; nested exception is NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{Df0wvxy6SpW7auwH1zseug}{127.0.0.1}{127.0.0.1:9300}]]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:359) ~[spring-beans-4.1.9.RELEASE.jar:4.1.9.RELEASE]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108) ~[spring-beans-4.1.9.RELEASE.jar:4.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1475) ~[spring-beans-4.1.9.RELEASE.jar:4.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1220) ~[spring-beans-4.1.9.RELEASE.jar:4.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537) ~[spring-beans-4.1.9.RELEASE.jar:4.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476) ~[spring-beans-4.1.9.RELEASE.jar:4.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303) ~[spring-beans-4.1.9.RELEASE.jar:4.1.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.1.9.RELEASE.jar:4.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299) ~[spring-beans-4.1.9.RELEASE.jar:4.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194) ~[spring-beans-4.1.9.RELEASE.jar:4.1.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755) ~[spring-beans-4.1.9.RELEASE.jar:4.1.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:762) ~[spring-context-4.1.9.RELEASE.jar:4.1.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480) ~[spring-context-4.1.9.RELEASE.jar:4.1.9.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:664) ~[spring-webmvc-4.1.9.RELEASE.jar:4.1.9.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:630) ~[spring-webmvc-4.1.9.RELEASE.jar:4.1.9.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:678) ~[spring-webmvc-4.1.9.RELEASE.jar:4.1.9.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:549) ~[spring-webmvc-4.1.9.RELEASE.jar:4.1.9.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:490) ~[spring-webmvc-4.1.9.RELEASE.jar:4.1.9.RELEASE]
	at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:136) ~[spring-webmvc-4.1.9.RELEASE.jar:4.1.9.RELEASE]
	at javax.servlet.GenericServlet.init(GenericServlet.java:158) ~[servlet-api.jar:3.1.FR]
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1241) ~[catalina.jar:8.0.15]
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1154) ~[catalina.jar:8.0.15]
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1041) ~[catalina.jar:8.0.15]
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4944) ~[catalina.jar:8.0.15]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5230) ~[catalina.jar:8.0.15]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) ~[catalina.jar:8.0.15]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) ~[catalina.jar:8.0.15]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) ~[catalina.jar:8.0.15]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714) ~[catalina.jar:8.0.15]
	at org.apache.catalina.startup.HostConfig.manageApp(HostConfig.java:1585) ~[catalina.jar:8.0.15]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:300) ~[tomcat-coyote.jar:8.0.15]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819) ~[?:1.8.0_112]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801) ~[?:1.8.0_112]
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:463) ~[catalina.jar:8.0.15]
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:413) ~[catalina.jar:8.0.15]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:300) ~[tomcat-coyote.jar:8.0.15]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819) ~[?:1.8.0_112]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801) ~[?:1.8.0_112]
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468) ~[?:1.8.0_112]
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76) ~[?:1.8.0_112]
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309) ~[?:1.8.0_112]
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401) ~[?:1.8.0_112]
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829) ~[?:1.8.0_112]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:324) ~[?:1.8.0_112]
	at sun.rmi.transport.Transport$1.run(Transport.java:200) ~[?:1.8.0_112]
	at sun.rmi.transport.Transport$1.run(Transport.java:197) ~[?:1.8.0_112]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_112]
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196) ~[?:1.8.0_112]
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568) ~[?:1.8.0_112]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826) ~[?:1.8.0_112]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683) ~[?:1.8.0_112]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_112]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]

**Comment by EdronCai** [comment]
我之前用的时候没有报这个错误

**Comment by gsh199449** [comment]
这个可能是你的elasticsearch没启动，或者是启动有问题，看下elasticsearch启动日志吧

**Comment by EdronCai** [comment]
是的 我用管理员的身份启动elasticsearch就可以了
